### ISSUE TITLE
ถ้าข้อความมีวงเล็บ (   )  แล้วโปรแกรม error ครับ

### ISSUE THREAD

**Issue by CakeZilla** [e23thr/thai-sentence-cut#15]
ตัวอย่าง

var str = "ทดสอบภาษาไทย (ตัวอย่าง)" 
var str_spilt = splitThaiStringByLength(str,10)
console.log(str_spilt)

<img width="552" alt="image" src="https://github.com/e23thr/thai-sentence-cut/assets/9818302/93a12150-10a1-40ae-8ba3-6411207a7bc6">

**Comment by e23thr** [comment]
ขอบคุณครับ เดี๋ยวยังไงผมแก้ไขให้ครับ แล้วจะจแ้งให้นะครับ

**Comment by e23thr** [comment]
@CakeZilla ขอโทษทีที่ช้านะครับ ถ้าเจอปัญหาอื่นอีกมาเปิด issue ใหม่ได้เลยนะครับ

**Comment by CakeZilla** [comment]
ขอบคุณมากครับผม :)
